<html>
    <head>
        <?php
            include_once("includes/rel.html")
        ?>
    </head>
    <body>
        <?php
            include_once("includes/navbar.html");
        ?>
    </body>
</html>